### ISSUE TITLE
Dataset License ?

### ISSUE THREAD

**Issue by wannaphong** [wongnai/wongnai-corpus#1]
Is Wongnai-corpus  LGPL License ? http://www.dcc.ac.uk/resources/how-guides/license-research-data

**Comment by Ekkalak-T** [comment]
Sorry for the late reply. Yes it is, the corpus is licensed under LGPL-3.0

[https://github.com/wongnai/wongnai-corpus/blob/master/LICENSE](url)

**Comment by wannaphong** [comment]
@Ekkalak-T  Thank you.
