### ISSUE TITLE
Is Restaurants data service still available? 

### ISSUE THREAD

**Issue by sahussawud** [wongnai/wongnai-corpus#4]
As link [https://business.wongnai.com/restaurants-data-service/en/](https://business.wongnai.com/restaurants-data-service/en/). It couldn't access. thank you

**Comment by whs** [comment]
Thanks for the inquiry. I've let our team know and we'll get in touch.

**Comment by whs** [comment]
Due to concerns from the new privacy-related laws, our restaurant information service is currently unavailable.
